# Generated by Django 4.0.2 on 2022-07-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'System user', 'verbose_name_plural': 'System users'},
        ),
    ]
