# Generated by Django 3.2 on 2022-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient'), ('office_manager', 'office_manager')], default='patient', max_length=255, null=True),
        ),
    ]
