# Generated by Django 3.0.7 on 2022-07-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='pictures',
            field=models.ManyToManyField(to='handbook.Pictures'),
        ),
        migrations.AddField(
            model_name='essentials',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
    ]
