# Generated by Django 3.2 on 2022-07-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='handbook',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='week',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handbook',
            name='mini_content',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essentials',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='handbook',
            name='pictures',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handbook.pictures'),
            preserve_default=False,
        ),
    ]
