# Generated by Django 3.2 on 2022-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_auto_20220712_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='week',
        ),
        migrations.AddField(
            model_name='article',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
