# Generated by Django 3.2 on 2022-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_auto_20220719_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handbook',
            name='pictures',
        ),
        migrations.AddField(
            model_name='handbook',
            name='baby_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='fruit_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
