# Generated by Django 3.2 on 2022-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0005_alter_advices_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='height',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handbook',
            name='weight',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
