# Generated by Django 3.2 on 2022-07-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_auto_20220712_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advices',
        ),
        migrations.RemoveField(
            model_name='handbook',
            name='mini_content',
        ),
        migrations.RemoveField(
            model_name='handbook',
            name='pictures',
        ),
        migrations.AddField(
            model_name='handbook',
            name='advices',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pictures',
            name='handbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handbook.handbook'),
            preserve_default=False,
        ),
    ]
