# Generated by Django 3.2 on 2022-07-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='check1',
        ),
        migrations.AddField(
            model_name='title',
            name='check_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='checklist.checklist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
