# Generated by Django 3.0.7 on 2022-07-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='med_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.MedCard'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
        migrations.AddField(
            model_name='answer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Question'),
        ),
    ]
