# Generated by Django 4.0.5 on 2022-06-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_answer_checklist_medcard_question_delete_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='medcard',
            name='question',
        ),
        migrations.AddField(
            model_name='medcard',
            name='question',
            field=models.ManyToManyField(to='checklist.question'),
        ),
    ]
