# Generated by Django 3.2 on 2022-08-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='recommandations',
            new_name='recommendations',
        ),
    ]
