# Generated by Django 4.0.5 on 2022-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
        migrations.AddField(
            model_name='medcard',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medcard',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
