# Generated by Django 3.2 on 2022-08-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.ManyToManyField(blank=True, related_name='friday', to='schedule.TimeSlots'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.ManyToManyField(blank=True, related_name='monday', to='schedule.TimeSlots'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.ManyToManyField(blank=True, related_name='saturday', to='schedule.TimeSlots'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.ManyToManyField(blank=True, related_name='sunday', to='schedule.TimeSlots'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.ManyToManyField(blank=True, related_name='thursday', to='schedule.TimeSlots'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.ManyToManyField(blank=True, related_name='tuesday', to='schedule.TimeSlots'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.ManyToManyField(blank=True, related_name='wednesday', to='schedule.TimeSlots'),
        ),
        migrations.AddField(
            model_name='holidays',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslots'),
        ),
    ]
