# Generated by Django 3.2 on 2022-08-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220815_1708'),
        ('schedule', '0003_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='users.doctor'),
        ),
    ]
