# Generated by Django 3.2 on 2022-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
