# Generated by Django 3.2 on 2022-08-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_arrived',
        ),
    ]
